hook .united_arab_emirates.utils
Removed in hooks.py
AttributeError: module 'erpnext.regional.united_arab_emirates.utils' has no attribute 'update_grand_total_for_rcm'